// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YgNk-Kyj42zPhfyiYCdMKMrp-6pfjKI',
    appId: '1:944070130732:web:37e4aaf1aaa0aa9180a589',
    messagingSenderId: '944070130732',
    projectId: 'learnsbuy-376d2',
    authDomain: 'learnsbuy-376d2.firebaseapp.com',
    storageBucket: 'learnsbuy-376d2.firebasestorage.app',
    measurementId: 'G-T3N0MMZ0RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9tP7VTd0pFCpLesQiFHtYv6VfgkiH-0',
    appId: '1:738481561377:android:c72f869d873d405431e860',
    messagingSenderId: '738481561377',
    projectId: 'learnsbuy-2af81',
    storageBucket: 'learnsbuy-2af81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNSwhMxkyfqULZIIjmnr0x7WjSKUoYrQ',
    appId: '1:738481561377:ios:bb2f25df3e99803931e860',
    messagingSenderId: '738481561377',
    projectId: 'learnsbuy-2af81',
    storageBucket: 'learnsbuy-2af81.firebasestorage.app',
    iosBundleId: 'com.learnsbuy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNSwhMxkyfqULZIIjmnr0x7WjSKUoYrQ',
    appId: '1:738481561377:ios:bb2f25df3e99803931e860',
    messagingSenderId: '738481561377',
    projectId: 'learnsbuy-2af81',
    storageBucket: 'learnsbuy-2af81.firebasestorage.app',
    iosBundleId: 'com.learnsbuy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9YgNk-Kyj42zPhfyiYCdMKMrp-6pfjKI',
    appId: '1:944070130732:web:d71f2b773937397d80a589',
    messagingSenderId: '944070130732',
    projectId: 'learnsbuy-376d2',
    authDomain: 'learnsbuy-376d2.firebaseapp.com',
    storageBucket: 'learnsbuy-376d2.firebasestorage.app',
    measurementId: 'G-CRQGG1KBHR',
  );
}
